name: terraform
on: [push, pull_request]

jobs:
  #Job 1
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init
      
    - name: Terraform Format
      working-directory: ./terraform
      run: |
        terraform fmt -check

    - name: Terraform Validate
      working-directory: ./terraform
      run: |
        terraform validate

    - name: Terraform Plan
      working-directory: ./terraform
      run: |
        terraform plan

    - name: Terraform Apply
      working-directory: ./terraform
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      run: |
        terraform apply -auto-approve
